// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haugevuppdeqeozesvom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhdWdldnVwcGRlcWVvemVzdm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjM4MDAsImV4cCI6MjA2ODg5OTgwMH0.9wSad8yuw9ZuvSIoAKtuvkDpx8bKhZE-hMRB0lK4GyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});